language: cpp
sudo: required
dist: trusty
compiler:
  - clang++
  - g++
os:
  - linux
  - osx
addons:
  apt:
    packages:
    - g++-4.8
    - clang-3.9
    - qt4-qmake
before_script:
  - git clone https://github.com/GravisZro/pdtk.git ../pdtk
script:
  - SPEC=$(echo $TRAVIS_OS_NAME-$CC | sed -e s/osx/macx/ -e s/gcc/g++/ -e s/\\\(.*\\\)-clang/unsupported\\/\\1-clang/)
  - qmake sxconfig.pro -spec $SPEC CONFIG+=debug && /usr/bin/make qmake_all
