language: cpp
sudo: required
dist: trusty
compiler:
  - clang++
  - g++
os:
  - linux
  - osx
cache:
  apt: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - qt4-qmake
before_install:
  - COMPILER_NAME=$(echo $CC | sed -e s/gcc/g++-7/ -e s/clang/clang-3.9/)
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt-get remove g++-4* gcc-4* clang-3.3* clang-3.4* clang-3.5* clang-3.8*; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew install qt; fi
before_script:
  - git clone https://github.com/GravisZro/pdtk.git ../pdtk
script:
  - SPEC=$(echo $TRAVIS_OS_NAME-$CC | sed -e s/osx/macx/ -e s/gcc/g++/ -e s/\\\(.*\\\)-clang/unsupported\\/\\1-clang/)
  - qmake sxconfig.pro -spec $SPEC CONFIG+=debug && make
