language: cpp
sudo: required
dist: trusty
compiler:
  - clang++
  - g++
os:
  - linux
  - osx
addons:
  apt:
    packages:
    - qt5-qmake
    - gcc-5
    - clang-3.8
before_script:
  - git clone https://github.com/GravisZro/pdtk.git pdtk
script:
  - SPEC=$(echo $TRAVIS_OS_NAME-$CC | sed -e s/osx/macx/ -e s/gcc/g++/)
  - qmake sxconfig.pro -spec $SPEC CONFIG+=debug && /usr/bin/make qmake_all
