language: cpp
sudo: required
dist: trusty
compiler:
  - clang++
  - g++
os:
  - linux
  - osx
addons:
  apt:
    packages:
    - qt4-qmake
before_install:
  - echo before install
  - pwd
  - qmake
before_script:
  - echo before script
  - pwd
  - qmake
script:
  - echo script
  - pwd
  - qmake
