language: cpp
sudo: required
dist: trusty
compiler:
  - clang++
  - g++
os:
  - linux
  - osx
cache:
  apt: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - qt4-qmake
before_install:
  - COMPILER_NAME=$(echo $CC | sed -e s/gcc/g++-7/ -e s/clang/clang-3.9/)
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
  - sudo ln -srf /usr/bin/asan_symbolize /usr/bin/asan_symbolize-3.9
  - sudo ln -srf /usr/bin/c-index-test /usr/bin/c-index-test-3.9
  - sudo ln -srf /usr/bin/clang++ /usr/bin/clang++-3.9
  - sudo ln -srf /usr/bin/clang /usr/bin/clang-3.9
  - sudo ln -srf /usr/bin/clang-apply-replacements /usr/bin/clang-apply-replacements-3.9
  - sudo ln -srf /usr/bin/clang-check /usr/bin/clang-check-3.9
  - sudo ln -srf /usr/bin/clang-cl /usr/bin/clang-cl-3.9
  - sudo ln -srf /usr/bin/clang-include-fixer /usr/bin/clang-include-fixer-3.9
  - sudo ln -srf /usr/bin/clang-query /usr/bin/clang-query-3.9
  - sudo ln -srf /usr/bin/clang-rename /usr/bin/clang-rename-3.9
  - sudo ln -srf /usr/bin/find-all-symbols /usr/bin/find-all-symbols-3.9
  - sudo ln -srf /usr/bin/modularize /usr/bin/modularize-3.9
  - sudo ln -srf /usr/bin/sancov /usr/bin/sancov-3.9
  - sudo ln -srf /usr/bin/scan-build /usr/bin/scan-build-3.9
  - sudo ln -srf /usr/bin/scan-build-py /usr/bin/scan-build-py-3.9
  - sudo ln -srf /usr/bin/scan-view /usr/bin/scan-view-3.9
  - sudo ln -srf /usr/bin/gcc /usr/bin/gcc-7
  - sudo ln -srf /usr/bin/g++ /usr/bin/g++-7
  - sudo ln -srf /usr/bin/cpp /usr/bin/cpp-7
  - sudo ln -srf /usr/bin/gcc-ar /usr/bin/gcc-ar-7
  - sudo ln -srf /usr/bin/gcc-nm /usr/bin/gcc-nm-7
  - sudo ln -srf /usr/bin/gcc-ranlib /usr/bin/gcc-ranlib-7
  - fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew install qt; fi
before_script:
  - git clone https://github.com/GravisZro/pdtk.git ../pdtk
script:
  - SPEC=$(echo $TRAVIS_OS_NAME-$CC | sed -e s/osx/macx/ -e s/gcc/g++/ -e s/\\\(.*\\\)-clang/unsupported\\/\\1-clang/)
  - qmake sxconfig.pro -spec $SPEC CONFIG+=debug && make
