language: cpp
sudo: required
dist: trusty
compiler:
  - clang++
  - g++
os:
  - linux
  - osx
cache:
  apt: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - debian-sid
    packages:
      - gcc-7-base/trusty
      - g++-7/trusty
      - gcc-7/trusty
      - cpp-7/trusty
      - libatomic1/trusty
      - libasan4/trusty
      - libgcc-7-dev/trusty
      - libgomp1/trusty
      - libitm1/trusty
      - libquadmath0/trusty
      - libstdc++-7-dev/trusty
      - libtsan0/trusty
      - qt5-qmake/sid
      - qtchooser/sid
before_install:
  - COMPILER_NAME=$(echo $CC | sed -e s/gcc/g++-7/ -e s/clang/clang-3.9/)
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew install qt5; brew link qt5 --force; fi
before_script:
  - git clone https://github.com/GravisZro/pdtk.git ../pdtk
script:
  - SPEC=$(echo $TRAVIS_OS_NAME-$CC | sed -e s/osx/macx/ -e s/gcc/g++/)
  - qmake sxconfig.pro -spec $SPEC CONFIG+=debug && make
