language: cpp
sudo: required
dist: trusty
compiler:
  - clang++
  - g++
os:
  - linux
  - osx
addons:
  apt:
    packages:
    - qt4-qmake
before_script:
  - git clone https://github.com/GravisZro/pdtk.git pdtk
  - qmake
script:
  - make
