language: cpp
sudo: required
dist: trusty
compiler:
  - clang++
  - g++
os:
  - linux
  - osx
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - g++-7
    - clang-3.9
    - qt5-qmake
before_script:
  - if [ $TRAVIS_OS_NAME = osx ] then brew install qt5; brew link qt5 --force; fi
  - git clone https://github.com/GravisZro/pdtk.git ../pdtk
script:
  - SPEC=$(echo $TRAVIS_OS_NAME-$CC | sed -e s/osx/macx/ -e s/gcc/g++/)
  - qmake sxconfig.pro -spec $SPEC CONFIG+=debug && make
