language: cpp
sudo: required
dist: trusty
compiler:
  - clang++
  - g++
os:
  - linux
  - osx
cache:
  apt: true
addons:
  apt:
    sources:
    - debian-sid
before_install:
  - COMPILER_NAME=$(echo $CC | sed -e s/gcc/g++-7/ -e s/clang/clang-3.9/)
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt-get update -qq; sudo apt-get install libc6 qt5-qmake $COMPILER_NAME; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew install qt5; brew link qt5 --force; fi
before_script:
  - git clone https://github.com/GravisZro/pdtk.git ../pdtk
script:
  - SPEC=$(echo $TRAVIS_OS_NAME-$CC | sed -e s/osx/macx/ -e s/gcc/g++/)
  - qmake sxconfig.pro -spec $SPEC CONFIG+=debug && make
