language: cpp
sudo: required
dist: trusty
compiler:
  - clang++
  - g++
os:
  - linux
  - osx
addons:
  apt:
    packages:
    - qt4-qmake
before_install:
  - echo before install
  - git clone https://github.com/GravisZro/pdtk.git pdtk
install:
  - echo install
before_script:
  - echo before script
script:
  - echo script
